/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab.pkg8_noelmartinez;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author noelg
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
        //sirve para que la pantalla se muestre centrada
        this.setLocationRelativeTo(null);
        //estos 3 primeros hilos es para controlar las horas que coloque en cada tab
        HiloHora h = new HiloHora(jl_hora);
        Thread proceso1 = new Thread(h);
        proceso1.start();

        HiloHora h2 = new HiloHora(jl_hora2);
        Thread proceso2 = new Thread(h2);
        proceso2.start();

        HiloHora h3 = new HiloHora(jl_hora3);
        Thread proceso3 = new Thread(h3);
        proceso3.start();
        //este hilo es para manejar el progress bar del estado del articulo
        administrarBarra ab = new administrarBarra(jp_estado);
        Thread llenado = new Thread(ab);
        llenado.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_sexo = new javax.swing.ButtonGroup();
        bg_civil = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jt_id = new javax.swing.JTextField();
        label_nombre = new javax.swing.JLabel();
        labelEdad = new javax.swing.JLabel();
        rb_m = new javax.swing.JRadioButton();
        jt_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rb_f = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        rb_soltero = new javax.swing.JRadioButton();
        rb_casado = new javax.swing.JRadioButton();
        rb_divorciado = new javax.swing.JRadioButton();
        rb_viudo = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jf_altura = new javax.swing.JFormattedTextField();
        jf_peso = new javax.swing.JFormattedTextField();
        bt_creargerente = new javax.swing.JButton();
        bt_crearPersona = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jp_contraseña = new javax.swing.JPasswordField();
        jt_usuario = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jt_cargo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jt_ocupacion = new javax.swing.JTextField();
        jt_tiempo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jt_sueldo = new javax.swing.JTextField();
        jt_horario = new javax.swing.JTextField();
        cb_registro = new javax.swing.JComboBox<>();
        jLabel37 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        sp_edad = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        jl_hora = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jt_titulo = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jt_color = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jt_puntuacion = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jt_descfig = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jt_instrucciones = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jt_desc = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jt_editorial = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jt_tamaño = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jt_garantia = new javax.swing.JTextField();
        bt_crearFigura = new javax.swing.JButton();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jt_volumen = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        bt_crearComic = new javax.swing.JButton();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jt_edicion = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jt_casa = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        jt_pais = new javax.swing.JTextField();
        bt_crearJuego = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        sp_estado = new javax.swing.JSpinner();
        jp_estado = new javax.swing.JProgressBar();
        jl_hora2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        cb_personas = new javax.swing.JComboBox<>();
        cb_articulos = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jb_eliminar = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jl_hora3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(219, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(219, 255, 255));
        jPanel4.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Identificacion:");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(12, 36, 86, 19);
        jPanel4.add(jt_id);
        jt_id.setBounds(108, 37, 220, 30);

        label_nombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label_nombre.setForeground(new java.awt.Color(0, 0, 0));
        label_nombre.setText("Nombre:");
        jPanel4.add(label_nombre);
        label_nombre.setBounds(55, 82, 53, 19);

        labelEdad.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelEdad.setForeground(new java.awt.Color(0, 0, 0));
        labelEdad.setText("Edad:");
        jPanel4.add(labelEdad);
        labelEdad.setBounds(55, 129, 37, 19);

        bg_sexo.add(rb_m);
        rb_m.setText("Masculino");
        jPanel4.add(rb_m);
        rb_m.setBounds(111, 173, 73, 23);
        jPanel4.add(jt_nombre);
        jt_nombre.setBounds(108, 83, 220, 30);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Sexo:");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(55, 174, 35, 19);

        bg_sexo.add(rb_f);
        rb_f.setText("Femenino");
        jPanel4.add(rb_f);
        rb_f.setBounds(184, 173, 71, 23);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Estado Civil:");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(12, 215, 78, 19);

        bg_civil.add(rb_soltero);
        rb_soltero.setText("Soltero(a)");
        jPanel4.add(rb_soltero);
        rb_soltero.setBounds(108, 214, 73, 23);

        bg_civil.add(rb_casado);
        rb_casado.setText("Casado(a)");
        jPanel4.add(rb_casado);
        rb_casado.setBounds(181, 214, 76, 23);

        bg_civil.add(rb_divorciado);
        rb_divorciado.setText("Divorciado(a)");
        jPanel4.add(rb_divorciado);
        rb_divorciado.setBounds(257, 214, 90, 23);

        bg_civil.add(rb_viudo);
        rb_viudo.setText("Viudo(a)");
        jPanel4.add(rb_viudo);
        rb_viudo.setBounds(347, 214, 67, 23);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Altura:");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(49, 263, 41, 19);

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Peso: ");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(50, 310, 40, 19);

        jf_altura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#.##"))));
        jPanel4.add(jf_altura);
        jf_altura.setBounds(102, 264, 123, 30);

        jf_peso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#.##"))));
        jPanel4.add(jf_peso);
        jf_peso.setBounds(102, 311, 123, 30);

        bt_creargerente.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bt_creargerente.setText("Crear Gerente");
        bt_creargerente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_creargerenteMouseClicked(evt);
            }
        });
        jPanel4.add(bt_creargerente);
        bt_creargerente.setBounds(569, 203, 138, 44);

        bt_crearPersona.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bt_crearPersona.setText("Crear Persona General ");
        bt_crearPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearPersonaMouseClicked(evt);
            }
        });
        jPanel4.add(bt_crearPersona);
        bt_crearPersona.setBounds(600, 550, 186, 44);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Opciones Exclusivas para Crear Gerentes:");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(503, 31, 298, 19);

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Usuario:");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(472, 68, 52, 19);

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Contraseña:");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(450, 106, 78, 19);
        jPanel4.add(jp_contraseña);
        jp_contraseña.setBounds(566, 96, 141, 30);
        jPanel4.add(jt_usuario);
        jt_usuario.setBounds(566, 58, 141, 30);

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Cargo:");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(480, 150, 43, 19);
        jPanel4.add(jt_cargo);
        jt_cargo.setBounds(570, 139, 141, 30);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Opciones Exclusivas Para crear Persona General:");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(558, 386, 348, 19);

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Ocupacion:");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(470, 417, 72, 31);

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Horario de trabajo:");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(430, 480, 118, 19);

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Tiempo de estar trabajando(semanas):");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(740, 420, 222, 33);
        jPanel4.add(jt_ocupacion);
        jt_ocupacion.setBounds(554, 424, 155, 30);
        jPanel4.add(jt_tiempo);
        jt_tiempo.setBounds(970, 419, 60, 30);

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Sueldo:");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(750, 470, 48, 19);
        jPanel4.add(jt_sueldo);
        jt_sueldo.setBounds(800, 470, 155, 30);
        jPanel4.add(jt_horario);
        jt_horario.setBounds(560, 480, 155, 23);

        jPanel4.add(cb_registro);
        cb_registro.setBounds(886, 100, 450, 30);

        jLabel37.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("PERSONAS");
        jPanel4.add(jLabel37);
        jLabel37.setBounds(130, 12, 72, 18);

        jLabel57.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(0, 0, 0));
        jLabel57.setText("Ingresado por:");
        jPanel4.add(jLabel57);
        jLabel57.setBounds(1060, 40, 103, 19);
        jPanel4.add(jSeparator3);
        jSeparator3.setBounds(0, 360, 420, 16);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator4);
        jSeparator4.setBounds(416, 0, 10, 358);

        sp_edad.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jPanel4.add(sp_edad);
        sp_edad.setBounds(110, 130, 50, 20);

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Hora:");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(303, 10, 40, 15);

        jl_hora.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jl_hora.setForeground(new java.awt.Color(0, 0, 0));
        jl_hora.setText("00:00:00");
        jPanel4.add(jl_hora);
        jl_hora.setBounds(350, 10, 64, 17);

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 670));

        jTabbedPane1.addTab("Crear Usuario y Articulos", jPanel2);

        jPanel6.setBackground(new java.awt.Color(219, 255, 255));
        jPanel6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("ARTICULOS");
        jPanel6.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 12, -1, -1));

        jLabel39.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText("Titulo:");
        jPanel6.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 42, -1, -1));
        jPanel6.add(jt_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 43, 81, 30));

        jLabel40.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 0));
        jLabel40.setText("Color:");
        jPanel6.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 100, -1, -1));

        jt_color.setEditable(false);
        jt_color.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_colorMouseClicked(evt);
            }
        });
        jPanel6.add(jt_color, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 101, 45, 30));

        jLabel41.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 0, 0));
        jLabel41.setText("Puntuacion:");
        jPanel6.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 42, -1, -1));
        jPanel6.add(jt_puntuacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 43, 53, 30));

        jLabel43.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 0, 0));
        jLabel43.setText("Opciones Exclusivas para Figuras: ");
        jPanel6.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, -1));

        jLabel44.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 0, 0));
        jLabel44.setText("Descripcion:");
        jPanel6.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 74, -1, -1));
        jPanel6.add(jt_descfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 75, 80, 30));

        jLabel45.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 0, 0));
        jLabel45.setText("Instrucciones:");
        jPanel6.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 138, -1, -1));
        jPanel6.add(jt_instrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 139, 110, 30));

        jLabel46.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 0, 0));
        jLabel46.setText("Descripcion:");
        jPanel6.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 89, -1, -1));
        jPanel6.add(jt_desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 86, 99, 27));

        jLabel47.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(0, 0, 0));
        jLabel47.setText("Editorial:");
        jPanel6.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 154, -1, -1));
        jPanel6.add(jt_editorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 155, 99, 30));

        jLabel48.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 0, 0));
        jLabel48.setText("Tamaño:");
        jPanel6.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 154, -1, -1));
        jPanel6.add(jt_tamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 155, 43, 30));

        jLabel49.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 0, 0));
        jLabel49.setText("Tiempo de Garantia:");
        jPanel6.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(726, 74, -1, -1));
        jPanel6.add(jt_garantia, new org.netbeans.lib.awtextra.AbsoluteConstraints(868, 75, 70, 30));

        bt_crearFigura.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bt_crearFigura.setText("Crear Figuras");
        bt_crearFigura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearFiguraMouseClicked(evt);
            }
        });
        jPanel6.add(bt_crearFigura, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, -1, 44));

        jLabel50.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 0, 0));
        jLabel50.setText("Opciones Exclusivas para Comic: ");
        jPanel6.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, -1, -1));

        jLabel51.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(0, 0, 0));
        jLabel51.setText("Volumen Descripcion:");
        jPanel6.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, -1, -1));
        jPanel6.add(jt_volumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 110, 30));

        jLabel52.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(0, 0, 0));
        jLabel52.setText("Estado del Producto(1-10):");
        jPanel6.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, -1, -1));

        bt_crearComic.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bt_crearComic.setText("Crear Comic");
        bt_crearComic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearComicMouseClicked(evt);
            }
        });
        jPanel6.add(bt_crearComic, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, -1, 44));

        jLabel53.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(0, 0, 0));
        jLabel53.setText("Opciones Exclusivas para Juegos:");
        jPanel6.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        jLabel54.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(0, 0, 0));
        jLabel54.setText("Edicion:");
        jPanel6.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 317, -1, -1));
        jPanel6.add(jt_edicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 318, 90, -1));

        jLabel55.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(0, 0, 0));
        jLabel55.setText("Casa de Elaboracion:");
        jPanel6.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 366, -1, -1));
        jPanel6.add(jt_casa, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 367, 100, -1));

        jLabel56.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(0, 0, 0));
        jLabel56.setText("Pais:");
        jPanel6.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 419, -1, -1));
        jPanel6.add(jt_pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 420, 135, -1));

        bt_crearJuego.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bt_crearJuego.setText("Crear Juego");
        bt_crearJuego.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearJuegoMouseClicked(evt);
            }
        });
        jPanel6.add(bt_crearJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 498, -1, 44));
        jPanel6.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 202, 420, 10));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel6.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 10, 200));

        sp_estado.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        jPanel6.add(sp_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, 60, -1));
        jPanel6.add(jp_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 300, 30));

        jl_hora2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jl_hora2.setForeground(new java.awt.Color(0, 0, 0));
        jl_hora2.setText("00:00:00");
        jPanel6.add(jl_hora2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, -1));

        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Hora:");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, -1));

        jTabbedPane1.addTab("Crear Articulo", jPanel6);

        jPanel5.setBackground(new java.awt.Color(219, 255, 255));

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Sexo", "Usuario/ocupacion", "Estado Civil"
            }
        ));
        jScrollPane1.setViewportView(tabla1);

        cb_personas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_personasItemStateChanged(evt);
            }
        });

        cb_articulos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_articulosItemStateChanged(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("Articulos:");

        jLabel35.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setText("Personas:");

        jb_eliminar.setText("ELIMINAR");
        jb_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_eliminarMouseClicked(evt);
            }
        });

        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Hora:");

        jl_hora3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jl_hora3.setForeground(new java.awt.Color(0, 0, 0));
        jl_hora3.setText("00:00:00");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 963, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel35)
                                    .addComponent(cb_personas, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(371, 371, 371)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb_articulos, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(426, 426, 426)
                                .addComponent(jb_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 323, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl_hora3)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_hora3)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_articulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_personas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jb_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(374, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Ver, Remover y Modificar", jPanel3);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 109, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab/pkg8_noelmartinez/logo.png"))); // NOI18N
        jLabel1.setText("GeekLandia");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 570, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 801, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_crearJuegoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearJuegoMouseClicked
        //este boton funciona para crear juegos
        while (true) {
            String contraseña = "";
            contraseña = JOptionPane.showInputDialog("Ingrese la clave para poder acceder: ");
            if (contraseña.equals("clau123")) {
                if (jt_titulo.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Debe llenar los campos de Articulo Primero!");
                } else {
                    String Titulo;
                    Color color;
                    String desc;
                    String editorial;
                    double tamaño;
                    int puntuacion;
                    Persona persona = null;
                    int edicion;
                    String CasaElaboracion;
                    String Pais;
                    try {
                        Titulo = jt_titulo.getText();
                        color = jt_color.getBackground();
                        desc = jt_desc.getText();
                        editorial = jt_editorial.getText();
                        tamaño = Double.parseDouble(jt_tamaño.getText());
                        puntuacion = Integer.parseInt(jt_puntuacion.getText());
                        edicion = Integer.parseInt(jt_edicion.getText());
                        CasaElaboracion = jt_casa.getText();
                        Pais = jt_pais.getText();
                        Articulo a = new Juegos(edicion, CasaElaboracion, Pais, Titulo, color, desc, editorial, tamaño, puntuacion, persona);
                        DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) cb_articulos.getModel();
                        modelo2.addElement(a);
                        cb_personas.setModel(modelo2);

                    } catch (Exception e) {
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(this, "Ocurrio un error, no se pudo guardar ningun dato");
                    }
                    JOptionPane.showMessageDialog(this, "Juego creado exitosamente");
                    jt_titulo.setText("");
                    jt_color.setBackground(Color.GRAY);
                    jt_desc.setText("");
                    jt_editorial.setText("");
                    jt_tamaño.setText("");
                    jt_puntuacion.setText("");
                    jt_edicion.setText("");
                    jt_casa.setText("");
                    jt_pais.setText("");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Contraseña no valida!");
            }
        }
    }//GEN-LAST:event_bt_crearJuegoMouseClicked

    private void bt_crearComicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearComicMouseClicked
        //este es para crear comics tambien con sus respectivos datos
        while (true) {
            String contraseña = "";
            contraseña = JOptionPane.showInputDialog("Ingrese la clave para poder acceder: ");
            if (contraseña.equals("clau123")) {
                if (jt_titulo.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Debe llenar los campos de Articulo Primero!");
                } else {
                    String Titulo;
                    Color color;
                    String desc;
                    String editorial;
                    double tamaño;
                    int puntuacion;
                    Persona persona = null;
                    int Estado;
                    int volumen_desc;

                    try {
                        Titulo = jt_titulo.getText();
                        color = jt_color.getBackground();
                        desc = jt_desc.getText();
                        editorial = jt_editorial.getText();
                        tamaño = Double.parseDouble(jt_tamaño.getText());
                        puntuacion = Integer.parseInt(jt_puntuacion.getText());
                        Estado = Integer.parseInt(sp_estado.getValue().toString());
                        volumen_desc = Integer.parseInt(jt_volumen.getText());
                        Articulo a = new Comic(volumen_desc, Estado, Titulo, color, desc, editorial, tamaño, puntuacion, persona);
                        DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) cb_articulos.getModel();
                        modelo2.addElement(a);
                        cb_personas.setModel(modelo2);

                    } catch (Exception e) {
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(this, "Ocurrio un error, no se pudo guardar ningun dato");
                    }
                    JOptionPane.showMessageDialog(this, "Comic creado exitosamente");
                    jt_titulo.setText("");
                    jt_color.setBackground(Color.GRAY);
                    jt_desc.setText("");
                    jt_editorial.setText("");
                    jt_tamaño.setText("");
                    jt_puntuacion.setText("");
                    sp_estado.setValue(0);
                    jt_volumen.setText("");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Contraseña no valida!");

            }
        }
    }

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {
        /*String Titulo;
        Color color;
        String desc;
        String editorial;
        double tamaño;
        int puntuacion;
        Persona persona = null;
        String descFig;
        String instrucciones;
        String garantia;
        try {
            Titulo = jt_titulo.getText();
            color = jt_color.getBackground();
            desc = jt_desc.getText();
            editorial = jt_editorial.getText();
            tamaño = Double.parseDouble(jt_tamaño.getText());
            puntuacion = Integer.parseInt(jt_puntuacion.getText());
            descFig = jt_descfig.getText();
            instrucciones = jt_instrucciones.getText();
            garantia = jt_garantia.getText();
            Articulo a = new Figura(descFig, instrucciones, garantia, Titulo, color, desc, editorial, tamaño, puntuacion, persona);
            DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) cb_articulos.getModel();
            modelo2.addElement(a);
            cb_personas.setModel(modelo2);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrio un error, no se pudo guardar ningun dato");
        }
        JOptionPane.showMessageDialog(this, "Figura creada exitosamente");
        jt_titulo.setText("");
        jt_color.setBackground(Color.GRAY);
        jt_desc.setText("");
        jt_editorial.setText("");
        jt_tamaño.setText("");
        jt_puntuacion.setText("");
        jt_descfig.setText("");
        jt_instrucciones.setText("");
        jt_garantia.setText("");*/
    }//GEN-LAST:event_bt_crearComicMouseClicked

    private void bt_crearFiguraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearFiguraMouseClicked
       //Este boton es para crear una figura con sus respectivos datos mas la seguridad pedida por la hermosa instructora :3
        while (true) {
            String contraseña = "";
            contraseña = JOptionPane.showInputDialog("Ingrese la clave para poder acceder: ");
            if (contraseña.equals("clau123")) {
                if (jt_titulo.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Debe llenar los campos de Articulo Primero!");
                } else {

                    String Titulo;
                    Color color;
                    String desc;
                    String editorial;
                    double tamaño;
                    int puntuacion;
                    Persona persona = null;
                    String descFig;
                    String instrucciones;
                    String garantia;
                    try {
                        Titulo = jt_titulo.getText();
                        color = jt_color.getBackground();
                        desc = jt_desc.getText();
                        editorial = jt_editorial.getText();
                        tamaño = Double.parseDouble(jt_tamaño.getText());
                        puntuacion = Integer.parseInt(jt_puntuacion.getText());
                        descFig = jt_descfig.getText();
                        instrucciones = jt_instrucciones.getText();
                        garantia = jt_garantia.getText();
                        Articulo a = new Figura(descFig, instrucciones, garantia, Titulo, color, desc, editorial, tamaño, puntuacion, persona);
                        DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) cb_articulos.getModel();
                        modelo2.addElement(a);
                        cb_personas.setModel(modelo2);
                    } catch (Exception e) {
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(this, "Ocurrio un error, no se pudo guardar ningun dato");
                    }
                    JOptionPane.showMessageDialog(this, "Figura creada exitosamente");
                    jt_titulo.setText("");
                    jt_color.setBackground(Color.GRAY);
                    jt_desc.setText("");
                    jt_editorial.setText("");
                    jt_tamaño.setText("");
                    jt_puntuacion.setText("");
                    jt_descfig.setText("");
                    jt_instrucciones.setText("");
                    jt_garantia.setText("");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Contraseña no valida!");
            }
        }
    }//GEN-LAST:event_bt_crearFiguraMouseClicked

    private void jt_colorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_colorMouseClicked
        //este boton setea el fondo al color elegido
        jt_color.setBackground(JColorChooser.showDialog(this, "Elija el color del producto: ", Color.GRAY));

    }//GEN-LAST:event_jt_colorMouseClicked

    private void jb_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_eliminarMouseClicked
        //Elimina fila de una table
        if (tabla1.getSelectedRow() >= 0) {
            DefaultTableModel modelo = (DefaultTableModel) tabla1.getModel();
            modelo.removeRow(tabla1.getSelectedRow());
            tabla1.setModel(modelo);
        }
    }//GEN-LAST:event_jb_eliminarMouseClicked

    private void cb_articulosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_articulosItemStateChanged
        //este combobox recibe los objetos instanceados del Articulo
        if (evt.getStateChange() == 2) {
            if (cb_articulos.getSelectedItem() instanceof Comic) {
                Comic c = (Comic) cb_articulos.getSelectedItem();

                Object[] newrow = {
                    c.getEstado(),
                    c.getVolumen_desc(),};
                DefaultTableModel modelo = (DefaultTableModel) tabla1.getModel();
                modelo.addRow(newrow);
                tabla1.setModel(modelo);
            }
            if (cb_personas.getSelectedItem() instanceof Juegos) {
                Juegos s = (Juegos) cb_articulos.getSelectedItem();

                Object[] newrow = {
                    s.getCasaElaboracion(),
                    s.getEdicion(),
                    s.getPais(),};
                DefaultTableModel modelo = (DefaultTableModel) tabla1.getModel();
                modelo.addRow(newrow);
                tabla1.setModel(modelo);
            }
            if (cb_personas.getSelectedItem() instanceof Figura) {
                Figura s = (Figura) cb_articulos.getSelectedItem();

                Object[] newrow = {
                    s.getDescFigura(),
                    s.getInstrucciones(),
                    s.getTiempoGarantia(),};
                DefaultTableModel modelo = (DefaultTableModel) tabla1.getModel();
                modelo.addRow(newrow);
                tabla1.setModel(modelo);
            }
        }
    }//GEN-LAST:event_cb_articulosItemStateChanged
    //este combobox recibe los objetos instanceados de persona
    private void cb_personasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_personasItemStateChanged
        if (evt.getStateChange() == 2) {
            if (cb_personas.getSelectedItem() instanceof Gerente) {
                Gerente s = (Gerente) cb_personas.getSelectedItem();

                Object[] newrow = {
                    s.getNombre(),
                    s.getSexo(),
                    s.getUsuario(),
                    s.getEstadoCivil(),};
                DefaultTableModel modelo = (DefaultTableModel) tabla1.getModel();
                modelo.addRow(newrow);
                tabla1.setModel(modelo);
            }
            if (cb_personas.getSelectedItem() instanceof PersonaGeneral) {
                PersonaGeneral s = (PersonaGeneral) cb_personas.getSelectedItem();

                Object[] newrow = {
                    s.getNombre(),
                    s.getSexo(),
                    s.getOcupacion(),
                    s.getEstadoCivil(),};
                DefaultTableModel modelo = (DefaultTableModel) tabla1.getModel();
                modelo.addRow(newrow);
                tabla1.setModel(modelo);
            }
        }
    }//GEN-LAST:event_cb_personasItemStateChanged

    private void bt_crearPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearPersonaMouseClicked
        //este boton es para crear la persona General
        while (true) {
            String contraseña = "";
            contraseña = JOptionPane.showInputDialog("Ingrese la clave para poder acceder: ");
            if (contraseña.equals("clau123")) {
                if (jt_nombre.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Debe llenar los campos de Persona Primero!");
                } else {
                    String ID, Usuario, Horario, SemanaTrabajando, Ocupacion;
                    String Nombre;
                    int Edad;
                    String Sexo = "";
                    String EstadoCivil = "";
                    double Altura, Peso, Sueldo;
                    try {
                        ID = jt_id.getText();
                        Nombre = jt_nombre.getText();
                        Edad = Integer.parseInt(sp_edad.getValue().toString());
                        if (rb_m.isSelected()) {
                            Sexo = "Masculino";
                        } else {
                            Sexo = "Femenino";
                        }
                        if (rb_soltero.isSelected()) {
                            EstadoCivil = "Soltero(a)";
                        } else if (rb_casado.isSelected()) {
                            EstadoCivil = "Casado(a)";
                        } else if (rb_divorciado.isSelected()) {
                            EstadoCivil = "Divorciado(a)";
                        } else if (rb_viudo.isSelected()) {
                            EstadoCivil = "Viudo(a)";
                        }
                        Altura = Double.parseDouble(jf_altura.getText());
                        Peso = Double.parseDouble(jf_peso.getText());
                        Ocupacion = jt_ocupacion.getText();
                        Horario = jt_horario.getText();
                        SemanaTrabajando = jt_tiempo.getText();
                        Sueldo = Double.parseDouble(jt_sueldo.getText());
                        Persona g2 = new PersonaGeneral(Ocupacion, Horario, Edad, Sueldo, ID, Nombre, Edad, Sexo, EstadoCivil, Altura, Peso);
                        DefaultComboBoxModel modelo3 = (DefaultComboBoxModel) cb_registro.getModel();
                        modelo3.addElement(g2);
                        cb_registro.setModel(modelo3);

                    } catch (Exception e) {
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(this, "Ocurrio un error, no se puedo guardar ningun dato");
                    }
                    JOptionPane.showMessageDialog(this, "Personal General creado exitosamente");
                    jt_id.setText("");
                    jt_nombre.setText("");
                    sp_edad.setValue(0);
                    jf_altura.setText("");
                    jf_peso.setText("");
                    jt_ocupacion.setText("");
                    jt_horario.setText("");
                    jt_tiempo.setText("");
                    jt_sueldo.setText("");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Contraseña no valida!");
            }
        }

    }//GEN-LAST:event_bt_crearPersonaMouseClicked
    
    private void bt_creargerenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_creargerenteMouseClicked
        //este boton es para crear un gerente y lo mete en su respectivo combo box
        while (true) {
            String contraseña = "clau123";
            contraseña = JOptionPane.showInputDialog("Ingrese la clave para poder acceder: ");
            if (contraseña.equals("clau123")) {
                if (jt_nombre.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Debe llenar los campos de Persona Primero!");
                } else {
                    String ID, Usuario, Contraseña, Cargo;
                    String Nombre;
                    int Edad;
                    String Sexo = "";
                    String EstadoCivil = "";
                    double Altura, Peso;
                    try {
                        ID = jt_id.getText();
                        Nombre = jt_nombre.getText();
                        Edad = Integer.parseInt(sp_edad.getValue().toString());
                        if (rb_m.isSelected()) {
                            Sexo = "Masculino";
                        } else {
                            Sexo = "Femenino";
                        }
                        if (rb_soltero.isSelected()) {
                            EstadoCivil = "Soltero(a)";
                        } else if (rb_casado.isSelected()) {
                            EstadoCivil = "Casado(a)";
                        } else if (rb_divorciado.isSelected()) {
                            EstadoCivil = "Divorciado(a)";
                        } else if (rb_viudo.isSelected()) {
                            EstadoCivil = "Viudo(a)";
                        }
                        Altura = Double.parseDouble(jf_altura.getText());
                        Peso = Double.parseDouble(jf_peso.getText());
                        Usuario = jt_usuario.getText();
                        Contraseña = jp_contraseña.getText();
                        Cargo = jt_cargo.getText();
                        Gerente g = new Gerente(Usuario, Contraseña, Cargo, ID, Nombre, Edad, Sexo, EstadoCivil, Altura, Peso);
                        DefaultComboBoxModel modelo1 = (DefaultComboBoxModel) cb_personas.getModel();
                        modelo1.addElement(g);
                        cb_personas.setModel(modelo1);

                        Persona g2 = new Gerente(Usuario, Contraseña, Cargo, ID, Nombre, Edad, Sexo, EstadoCivil, Altura, Peso);
                        DefaultComboBoxModel modelo3 = (DefaultComboBoxModel) cb_registro.getModel();
                        modelo3.addElement(g2);
                        cb_registro.setModel(modelo3);

                    } catch (Exception e) {
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(this, "Ocurrio un error, no se puedo guardar ningun dato");
                    }
                    JOptionPane.showMessageDialog(this, "Gerente creado exitosamente");
                    jt_id.setText("");
                    jt_nombre.setText("");
                    sp_edad.setValue(0);
                    jf_altura.setText("");
                    jf_peso.setText("");
                    jt_usuario.setText("");
                    jp_contraseña.setText("");
                    jt_cargo.setText("");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Contraseña no valida!");
            }
        }

    }//GEN-LAST:event_bt_creargerenteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }
    ArrayList<Articulo> articulos = new ArrayList();
    ArrayList<Persona> contactos = new ArrayList();
    Color color;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_civil;
    private javax.swing.ButtonGroup bg_sexo;
    private javax.swing.JButton bt_crearComic;
    private javax.swing.JButton bt_crearFigura;
    private javax.swing.JButton bt_crearJuego;
    private javax.swing.JButton bt_crearPersona;
    private javax.swing.JButton bt_creargerente;
    private javax.swing.JComboBox<String> cb_articulos;
    private javax.swing.JComboBox<String> cb_personas;
    private javax.swing.JComboBox<String> cb_registro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jb_eliminar;
    private javax.swing.JFormattedTextField jf_altura;
    private javax.swing.JFormattedTextField jf_peso;
    private javax.swing.JLabel jl_hora;
    private javax.swing.JLabel jl_hora2;
    private javax.swing.JLabel jl_hora3;
    private javax.swing.JPasswordField jp_contraseña;
    private javax.swing.JProgressBar jp_estado;
    private javax.swing.JTextField jt_cargo;
    private javax.swing.JTextField jt_casa;
    private javax.swing.JTextField jt_color;
    private javax.swing.JTextField jt_desc;
    private javax.swing.JTextField jt_descfig;
    private javax.swing.JTextField jt_edicion;
    private javax.swing.JTextField jt_editorial;
    private javax.swing.JTextField jt_garantia;
    private javax.swing.JTextField jt_horario;
    private javax.swing.JTextField jt_id;
    private javax.swing.JTextField jt_instrucciones;
    private javax.swing.JTextField jt_nombre;
    private javax.swing.JTextField jt_ocupacion;
    private javax.swing.JTextField jt_pais;
    private javax.swing.JTextField jt_puntuacion;
    private javax.swing.JTextField jt_sueldo;
    private javax.swing.JTextField jt_tamaño;
    private javax.swing.JTextField jt_tiempo;
    private javax.swing.JTextField jt_titulo;
    private javax.swing.JTextField jt_usuario;
    private javax.swing.JTextField jt_volumen;
    private javax.swing.JLabel labelEdad;
    private javax.swing.JLabel label_nombre;
    private javax.swing.JRadioButton rb_casado;
    private javax.swing.JRadioButton rb_divorciado;
    private javax.swing.JRadioButton rb_f;
    private javax.swing.JRadioButton rb_m;
    private javax.swing.JRadioButton rb_soltero;
    private javax.swing.JRadioButton rb_viudo;
    private javax.swing.JSpinner sp_edad;
    private javax.swing.JSpinner sp_estado;
    private javax.swing.JTable tabla1;
    // End of variables declaration//GEN-END:variables
}
